"""OS networking: routes, TUN adapter, foreign VPNs, underlay NIC."""

from desktop.net._impl import (  # noqa: F401
    RUSTDESK_PORTS,
    RUSTDESK_PROCS,
    TUN_IFACE_NAME,
    TUN_LAN_CIDR,
    TUN_SPLIT_HOPS,
    TunManager,
    apply_tun_iface_mtu,
    default_route_lines,
    detect_bind_interface,
    direct_python_paths,
    ensure_tun_split_default,
    foreign_vpn_live,
    foreign_vpn_processes,
    gateway_via_dest,
    iface_ipv4s,
    is_virtual_underlay,
    leftover_vpn_default_cmds,
    leftover_vpn_ifaces,
    our_tun_split_leftover,
    reclaim_tun_default,
    remove_stale_tun_adapter,
    run_leftover_vpn_default_cmds,
    run_route_cmds,
    stale_default_cmds,
    tun_iface_cidr,
    tun_owns_default,
    underlay_ifaces,
    wait_tun_iface,
    win_if_alias,
    win_if_index_by_alias,
)

__all__ = [
    "TUN_IFACE_NAME",
    "TunManager",
    "default_route_lines",
    "detect_bind_interface",
    "ensure_tun_split_default",
    "foreign_vpn_live",
    "wait_tun_iface",
]
