"""Typed application config."""

from desktop.config.constants import (
    AWG_DEFAULT_ADDRESS,
    AWG_DEFAULT_MTU,
    AWG_DEFAULT_PORT,
    BLOCKED_HOSTS,
    CORPORATE_BYPASS_PRESET,
    CORPORATE_PROXY_PRESET,
    HY2_DEFAULT_SNI,
    REALITY_DEFAULT_SNI,
    STANDARD_BYPASS_PRESET,
    TUN_DEFAULT_MTU,
)
from desktop.config.model import (
    AmneziaWgConfig,
    AppConfig,
    Hysteria2Config,
    ReverseSshConfig,
    ServerConfig,
    TransportConfig,
    TunConfig,
    as_bool,
    as_int,
    assign_filled,
    default_amneziawg_block,
    default_config_template,
    ensure_config_defaults,
    filled_str,
    normalize_dial,
    normalize_hy2_sni,
    normalize_scope,
    truthy,
)

__all__ = [
    "AWG_DEFAULT_ADDRESS",
    "AWG_DEFAULT_MTU",
    "AWG_DEFAULT_PORT",
    "BLOCKED_HOSTS",
    "CORPORATE_BYPASS_PRESET",
    "CORPORATE_PROXY_PRESET",
    "HY2_DEFAULT_SNI",
    "REALITY_DEFAULT_SNI",
    "STANDARD_BYPASS_PRESET",
    "TUN_DEFAULT_MTU",
    "AmneziaWgConfig",
    "AppConfig",
    "Hysteria2Config",
    "ReverseSshConfig",
    "ServerConfig",
    "TransportConfig",
    "TunConfig",
    "as_bool",
    "as_int",
    "assign_filled",
    "default_amneziawg_block",
    "default_config_template",
    "ensure_config_defaults",
    "filled_str",
    "normalize_dial",
    "normalize_hy2_sni",
    "normalize_scope",
    "truthy",
]
