"""Product name and identifiers (ERGOMS SECURE CONNECTION)."""

from __future__ import annotations

import os

APP_NAME = "ERGOMS SECURE CONNECTION"
APP_ID = "ergoms-secure-connection"
APP_EXE = "ErgomsSecureConnection"
ORG_NAME = "ERGOMS"

ENV_DATA = "ERGOMS_SC_DATA"
ENV_AUTOSTART = "ERGOMS_SC_AUTOSTART"
ENV_WATCHDOG_CHILD = "ERGOMS_SC_WATCHDOG_CHILD"
ENV_GUI = "ERGOMS_SC_GUI"
ENV_RESUME = "ERGOMS_SC_RESUME"
ENV_PYTHON = "ERGOMS_SC_PYTHON"
ENV_SOCKS = "ERGOMS_SC_SOCKS"
ENV_HTTP_PROXY = "ERGOMS_SC_HTTP_PROXY"
ENV_CONNECT_ALLOW = "ERGOMS_SC_CONNECT_ALLOW"
ENV_DOCKER_HOST_IP = "ERGOMS_SC_DOCKER_HOST_IP"
ENV_NO_ELEVATE = "ERGOMS_SC_NO_ELEVATE"

_LEGACY = {
    ENV_DATA: ("ERGOMS_VPN_DATA", "OPS_CONTENT_DATA"),
    ENV_AUTOSTART: ("ERGOMS_VPN_AUTOSTART", "OPS_CONTENT_AUTOSTART"),
    ENV_WATCHDOG_CHILD: ("ERGOMS_VPN_WATCHDOG_CHILD", "OPS_CONTENT_WATCHDOG_CHILD"),
    ENV_GUI: ("ERGOMS_VPN_GUI", "OPS_CONTENT_GUI"),
    ENV_RESUME: ("ERGOMS_VPN_RESUME",),
    ENV_PYTHON: ("ERGOMS_VPN_PYTHON", "OPS_CONTENT_PYTHON"),
    ENV_SOCKS: ("ERGOMS_VPN_SOCKS", "OPS_CONTENT_SOCKS"),
    ENV_HTTP_PROXY: ("ERGOMS_VPN_HTTP_PROXY", "OPS_CONTENT_HTTP_PROXY"),
    ENV_CONNECT_ALLOW: ("ERGOMS_VPN_CONNECT_ALLOW", "OPS_CONTENT_CONNECT_ALLOW"),
    ENV_DOCKER_HOST_IP: ("ERGOMS_VPN_DOCKER_HOST_IP", "OPS_CONTENT_DOCKER_HOST_IP"),
}


def env(name: str, default: str = "") -> str:
    val = (os.environ.get(name) or "").strip()
    if val:
        return val
    for legacy in _LEGACY.get(name, ()):
        val = (os.environ.get(legacy) or "").strip()
        if val:
            return val
    return default
